/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.users.routines.references


import by.anatolyloyko.ams.orm.jooq.schemas.users.routines.CreateUser

import org.jooq.Configuration



/**
 * Call <code>users.create_user</code>
 */
fun createUser(
      configuration: Configuration
    , _Id: Long?
): Unit {
    val p = CreateUser()
    p.set_Id(_Id)

    p.execute(configuration)
}
