/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.brands.routines


import by.anatolyloyko.ams.orm.jooq.schemas.brands.Brands

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateBrand : AbstractRoutine<java.lang.Void>("create_brand", Brands.BRANDS) {
    companion object {

        /**
         * The parameter <code>brands.create_brand._id</code>.
         */
        val _ID: Parameter<Long?> = Internal.createParameter("_id", SQLDataType.BIGINT, false, false)
    }

    init {
        addInParameter(CreateBrand._ID)
    }

    /**
     * Set the <code>_id</code> parameter IN value to the routine
     */
    fun set_Id(value: Long?): Unit = setValue(CreateBrand._ID, value)
}
