/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas


import by.anatolyloyko.ams.orm.jooq.schemas.tables.Studio

import kotlin.collections.List

import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Studios : SchemaImpl("studios", null) {
    companion object {

        /**
         * The reference instance of <code>studios</code>
         */
        val STUDIOS: Studios = Studios()
    }

    /**
     * The table <code>studios.studio</code>.
     */
    val STUDIO: Studio get() = Studio.STUDIO

    override fun getTables(): List<Table<*>> = listOf(
        Studio.STUDIO
    )
}
