/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.tables.references


import by.anatolyloyko.ams.orm.jooq.schemas.tables.Brand
import by.anatolyloyko.ams.orm.jooq.schemas.tables.BrandRoles
import by.anatolyloyko.ams.orm.jooq.schemas.tables.BrandStudios
import by.anatolyloyko.ams.orm.jooq.schemas.tables.Permission
import by.anatolyloyko.ams.orm.jooq.schemas.tables.Role
import by.anatolyloyko.ams.orm.jooq.schemas.tables.RolePermissions
import by.anatolyloyko.ams.orm.jooq.schemas.tables.Studio
import by.anatolyloyko.ams.orm.jooq.schemas.tables.StudioRoles
import by.anatolyloyko.ams.orm.jooq.schemas.tables.User
import by.anatolyloyko.ams.orm.jooq.schemas.tables.UserRoles



/**
 * The table <code>administration.brand</code>.
 */
val BRAND: Brand = Brand.BRAND

/**
 * The table <code>administration.brand_roles</code>.
 */
val BRAND_ROLES: BrandRoles = BrandRoles.BRAND_ROLES

/**
 * The table <code>administration.brand_studios</code>.
 */
val BRAND_STUDIOS: BrandStudios = BrandStudios.BRAND_STUDIOS

/**
 * The table <code>administration.permission</code>.
 */
val PERMISSION: Permission = Permission.PERMISSION

/**
 * The table <code>administration.role</code>.
 */
val ROLE: Role = Role.ROLE

/**
 * The table <code>administration.role_permissions</code>.
 */
val ROLE_PERMISSIONS: RolePermissions = RolePermissions.ROLE_PERMISSIONS

/**
 * The table <code>administration.studio</code>.
 */
val STUDIO: Studio = Studio.STUDIO

/**
 * The table <code>administration.studio_roles</code>.
 */
val STUDIO_ROLES: StudioRoles = StudioRoles.STUDIO_ROLES

/**
 * The table <code>administration.user</code>.
 */
val USER: User = User.USER

/**
 * The table <code>administration.user_roles</code>.
 */
val USER_ROLES: UserRoles = UserRoles.USER_ROLES
