/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.routines


import by.anatolyloyko.ams.orm.jooq.schemas.Brands

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SaveBrand : AbstractRoutine<Long>("save_brand", Brands.BRANDS, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter <code>brands.save_brand.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>brands.save_brand.i_id</code>.
         */
        val I_ID: Parameter<Long?> = Internal.createParameter("i_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>brands.save_brand.i_name</code>.
         */
        val I_NAME: Parameter<String?> = Internal.createParameter("i_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>brands.save_brand.i_description</code>.
         */
        val I_DESCRIPTION: Parameter<String?> = Internal.createParameter("i_description", SQLDataType.VARCHAR, false, false)
    }

    init {
        returnParameter = SaveBrand.RETURN_VALUE
        addInParameter(SaveBrand.I_ID)
        addInParameter(SaveBrand.I_NAME)
        addInParameter(SaveBrand.I_DESCRIPTION)
    }

    /**
     * Set the <code>i_id</code> parameter IN value to the routine
     */
    fun setIId(value: Long?): Unit = setValue(SaveBrand.I_ID, value)

    /**
     * Set the <code>i_id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIId(field: Field<Long?>): Unit {
        setField(SaveBrand.I_ID, field)
    }

    /**
     * Set the <code>i_name</code> parameter IN value to the routine
     */
    fun setIName(value: String?): Unit = setValue(SaveBrand.I_NAME, value)

    /**
     * Set the <code>i_name</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIName(field: Field<String?>): Unit {
        setField(SaveBrand.I_NAME, field)
    }

    /**
     * Set the <code>i_description</code> parameter IN value to the routine
     */
    fun setIDescription(value: String?): Unit = setValue(SaveBrand.I_DESCRIPTION, value)

    /**
     * Set the <code>i_description</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setIDescription(field: Field<String?>): Unit {
        setField(SaveBrand.I_DESCRIPTION, field)
    }
}
