services:
  user_db:
    image: postgres:17.2-alpine3.21
    container_name: user_db
    restart: always
    ports:
        - "5441:5432"
    volumes:
      - user_db_volume:/var/lib/postgresql/data
    env_file:
      - user-service/.env

  liquibase_user_db:
    image: liquibase/liquibase:latest
    container_name: liquibase_user_db
    env_file:
      - user-service/.env
    depends_on:
      - user_db
    volumes:
      - ./user-service/database/changelog:/liquibase/changelog
    command: update

  brand_db:
    image: postgres:17.2-alpine3.21
    container_name: brand_db
    restart: always
    ports:
      - "5442:5432"
    volumes:
      - brand_db_volume:/var/lib/postgresql/data
    env_file:
      - brand-service/.env

  liquibase_brand_db:
    image: liquibase/liquibase:latest
    container_name: liquibase_brand_db
    env_file:
      - brand-service/.env
    depends_on:
      - brand_db
    volumes:
      - ./brand-service/database/changelog:/liquibase/changelog
    command: update

  studio_db:
    image: postgres:17.2-alpine3.21
    container_name: studio_db
    restart: always
    ports:
      - "5443:5432"
    volumes:
      - studio_db_volume:/var/lib/postgresql/data
    env_file:
      - studio-service/.env

  liquibase_studio_db:
    image: liquibase/liquibase:latest
    container_name: liquibase_studio_db
    env_file:
      - studio-service/.env
    depends_on:
      - studio_db
    volumes:
      - ./studio-service/database/changelog:/liquibase/changelog
    command: update

volumes:
  user_db_volume:
  brand_db_volume:
  studio_db_volume:
