services:
  user_db:
    image: postgres:17.2-alpine3.21
    container_name: user_db
    restart: always
    ports:
        - "5441:5432"
    volumes:
      - user_db_volume:/var/lib/postgresql/data
    env_file:
      - user-service/.env

  liquibase_user_db:
    image: liquibase/liquibase:latest
    container_name: liquibase_user_db
    env_file:
      - user-service/.env
    depends_on:
      - user_db
    volumes:
      - ./user-service/database/changelog:/liquibase/changelog
    command: update

volumes:
  user_db_volume:
