services:
  redis:
    image: redis:7.4.10-alpine
    hostname: redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"

  config-server:
    image: springcloud/spring-cloud-kubernetes-configserver:5.0.2-SNAPSHOT
    hostname: config-server
    container_name: config-server
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED: false
      SPRING_CLOUD_KUBERNETES_SECRETS_ENABLED: false
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/tvoe-zdorovje/ams.git"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: "/config,/config/{application}"
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: "master"
      LOGGING_LEVEL_ROOT: INFO
      SERVER_PORT: 8888

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: "keycloak"
    command: start --import-realm
    volumes:
      - ./infrastructure/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      keycloak_db:
        condition: service_healthy
    healthcheck:
      test:  ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && grep -q '200 OK' <&3"]
      interval: 5s
      timeout: 5s
      retries: 100
    ports:
      - "8123:8080"
    env_file:
      - ./infrastructure/keycloak/.env
