services:
  router:
    image: ghcr.io/apollographql/router:v2.2.0
    container_name: router
    restart: on-failure
    depends_on:
      gateway-service:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./gateway/apollo/router/build/:/dist/mnt/:ro
    environment:
      APOLLO_ROUTER_SUPERGRAPH_PATH: /dist/mnt/schema/supergraph.graphql
      APOLLO_ROUTER_CONFIG_PATH: /dist/mnt/config/router.yaml
    env_file:
      - gateway/.env

  gateway-service:
    image: ghcr.io/tvoe-zdorovje/ams/gateway-service:0.2.0
    container_name: gateway
    restart: on-failure
    depends_on:
      auth-service:
        condition: service_healthy
      administration-service:
        condition: service_healthy
      appointment-service:
        condition: service_healthy
      brand-service:
        condition: service_healthy
      studio-service:
        condition: service_healthy
      user_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/layers/paketo-buildpacks_health-checker/thc/bin/thc" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 15s
    ports:
      - "8100:8100"
    env_file:
      - gateway/.env

  auth-service:
    image: ghcr.io/tvoe-zdorovje/ams/auth-service:latest
    container_name: auth-service
    restart: on-failure
    depends_on:
      liquibase_user_db:
        condition: service_completed_successfully
      liquibase_administration_db:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/layers/paketo-buildpacks_health-checker/thc/bin/thc"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 50s
    ports:
      - "8180:8180"
    env_file:
      - auth-service/.env

  administration-service:
    image: ghcr.io/tvoe-zdorovje/ams/administration-service:latest
    container_name: administration-service
    restart: on-failure
    depends_on:
      liquibase_administration_db:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/layers/paketo-buildpacks_health-checker/thc/bin/thc"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 50s
    ports:
      - "8181:8181"
    env_file:
      - administration-service/.env
  
  appointment-service:
    image: ghcr.io/tvoe-zdorovje/ams/appointment-service:latest
    container_name: appointment-service
    restart: on-failure
    depends_on:
      liquibase_administration_db:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/layers/paketo-buildpacks_health-checker/thc/bin/thc"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 50s
    ports:
      - "8182:8182"
    env_file:
      - appointment-service/.env
    
  brand-service:
    image: ghcr.io/tvoe-zdorovje/ams/brand-service:latest
    container_name: brand-service
    restart: on-failure
    depends_on:
      liquibase_brand_db:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "/layers/paketo-buildpacks_health-checker/thc/bin/thc" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 50s
    ports:
      - "8183:8183"
    env_file:
      - brand-service/.env
  
  studio-service:
    image: ghcr.io/tvoe-zdorovje/ams/studio-service:latest
    container_name: studio-service
    restart: on-failure
    depends_on:
      liquibase_studio_db:
        condition: service_completed_successfully
    ports:
      - "8184:8184"
    healthcheck:
      test: [ "CMD", "/layers/paketo-buildpacks_health-checker/thc/bin/thc" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 50s
    env_file:
      - studio-service/.env
  
  user-service:
    image: ghcr.io/tvoe-zdorovje/ams/user-service:latest
    container_name: user-service
    restart: on-failure
    depends_on:
      liquibase_user_db:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "/layers/paketo-buildpacks_health-checker/thc/bin/thc" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 50s
    ports:
      - "8185:8185"
    env_file:
      - user-service/.env
