federation_version: =2.5.1

subgraphs:
  administration:
    routing_url: http://administration-service/graphql
    schema:
      file: ./schemas/administration.graphqls

  appointments:
    routing_url: http://appointment-service/graphql
    schema:
      file: ./schemas/appointment.graphqls

  brands:
    routing_url: http://brand-service/graphql
    schema:
      file: ./schemas/brand.graphqls

  studios:
    routing_url: http://studio-service/graphql
    schema:
      file: ./schemas/studio.graphqls

  users:
    routing_url: http://user-service/graphql
    schema:
      file: ./schemas/user.graphqls
