/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.studios.routines


import by.anatolyloyko.ams.orm.jooq.schemas.studios.Studios

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateStudio : AbstractRoutine<java.lang.Void>("create_studio", Studios.STUDIOS) {
    companion object {

        /**
         * The parameter <code>studios.create_studio._id</code>.
         */
        val _ID: Parameter<Long?> = Internal.createParameter("_id", SQLDataType.BIGINT, false, false)
    }

    init {
        addInParameter(CreateStudio._ID)
    }

    /**
     * Set the <code>_id</code> parameter IN value to the routine
     */
    fun set_Id(value: Long?): Unit = setValue(CreateStudio._ID, value)
}
