package `by`.anatolyloyko.ams.orm.exposed.schemas.users.table

import kotlin.Long
import kotlin.String
import kotlin.Suppress
import org.jetbrains.exposed.sql.Column
import org.jetbrains.exposed.sql.Table

/**
 *
 *  *  ██████████████████████████ DO NOT MODIFY! █████████████████████████
 *  *  █                                             
 *  *  █                    It's an autogenerated file.
 *  *  █     To regenerate, execute:
 *  *  █ ./gradlew :user-service:generateDatabaseSchema
 *  *  █
 *  *  ███████████████████████████████████████████████████████████████████
 *
 *  Represents the "users.user_password" table in the database.
 *  
 *  Defines the structure to facilitate database operations using the Exposed library.
 */
@Suppress("MagicNumber")
internal object UserPasswordTable : Table("users.user_password") {
  public val userId: Column<Long> = long("user_id")

  public val password: Column<String> = text("password")

  override val primaryKey: Table.PrimaryKey = PrimaryKey(userId)
}
