package `by`.anatolyloyko.ams.orm.exposed.schemas.users.table

import kotlin.Long
import kotlin.String
import kotlin.Suppress
import org.jetbrains.exposed.sql.Column
import org.jetbrains.exposed.sql.Table

/**
 *
 *  *  ██████████████████████████ DO NOT MODIFY! █████████████████████████
 *  *  █                                             
 *  *  █                    It's an autogenerated file.
 *  *  █     To regenerate, execute:
 *  *  █ ./gradlew :user-service:generateDatabaseSchema
 *  *  █
 *  *  ███████████████████████████████████████████████████████████████████
 *
 *  Represents the "users.user" table in the database.
 *  
 *  Defines the structure to facilitate database operations using the Exposed library.
 */
@Suppress("MagicNumber")
internal object UserTable : Table("users.user") {
  public val id: Column<Long> = long("id")

  public val firstName: Column<String> = varchar("first_name", 50)

  public val lastName: Column<String> = varchar("last_name", 50)

  public val phoneNumber: Column<String> = varchar("phone_number", 15)

  override val primaryKey: Table.PrimaryKey = PrimaryKey(id)
}
