postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 15.4.0-debian-11-r45
  auth:
    existingSecret: "user-service-postgresql"
  primary:
    persistence:
      enabled: true
      size: 1Gi
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      mountPath: /bitnami/postgresql
      storageClass: standard
    resources:
      requests:
        cpu: 125m
        memory: 256Mi
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 560
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 10
      successThreshold: 1
    initdb:
      scriptsSecret: postgres-init-scripts

service:
  secrets:
    - name: user-service-postgresql

liquibase:
  enabled: true
  secrets:
    - name: user-service-liquibase

global:
  secrets:
    - name: user-service-postgresql
      type: Opaque
      data:
        DBHOST: "user-service-postgresql" # <release-name>-postgresql
        DBPORT: "5432"
        DBNAME: "user_db"
        database: "user_db"
        DBUSER: "ussportal"
        username: "ussportal"
        DBPASS: "ussportal"
        password: "ussportal"
        postgres-password: "pass"
    - name: user-service-liquibase
      type: Opaque
      data:
        PGHOST: "user-service-postgresql" # <release-name>-postgresql
        PGPORT: "5432"
        PGUSER: "ussliquibase"
        PGPASSWORD: "ussliquibase"
        PGDATABASE: "user_db"
