/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.brands.routines


import by.anatolyloyko.ams.orm.jooq.schemas.brands.Brands

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateBrand : AbstractRoutine<java.lang.Void>("create_brand", Brands.BRANDS) {
    companion object {

        /**
         * The parameter <code>brands.create_brand.i_name</code>.
         */
        val I_NAME: Parameter<String?> = Internal.createParameter("i_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>brands.create_brand.i_description</code>.
         */
        val I_DESCRIPTION: Parameter<String?> = Internal.createParameter("i_description", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>brands.create_brand.i_owner_user_id</code>.
         */
        val I_OWNER_USER_ID: Parameter<Long?> = Internal.createParameter("i_owner_user_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>brands.create_brand.o_id</code>.
         */
        val O_ID: Parameter<Long?> = Internal.createParameter("o_id", SQLDataType.BIGINT, false, false)
    }

    init {
        addInParameter(CreateBrand.I_NAME)
        addInParameter(CreateBrand.I_DESCRIPTION)
        addInParameter(CreateBrand.I_OWNER_USER_ID)
        addOutParameter(CreateBrand.O_ID)
        setSQLUsable(false)
    }

    /**
     * Set the <code>i_name</code> parameter IN value to the routine
     */
    fun setIName(value: String?): Unit = setValue(CreateBrand.I_NAME, value)

    /**
     * Set the <code>i_description</code> parameter IN value to the routine
     */
    fun setIDescription(value: String?): Unit = setValue(CreateBrand.I_DESCRIPTION, value)

    /**
     * Set the <code>i_owner_user_id</code> parameter IN value to the routine
     */
    fun setIOwnerUserId(value: Long?): Unit = setValue(CreateBrand.I_OWNER_USER_ID, value)

    /**
     * Get the <code>o_id</code> parameter OUT value from the routine
     */
    fun getOId(): Long? = get(CreateBrand.O_ID)
}
