/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.users.tables.references


import by.anatolyloyko.ams.orm.jooq.schemas.users.tables.User



/**
 * The table <code>users.user</code>.
 */
val USER: User = User.USER
