/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.tables.records


import by.anatolyloyko.ams.orm.jooq.schemas.administration.tables.Role

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RoleRecord private constructor() : UpdatableRecordImpl<RoleRecord>(Role.ROLE), Record4<Long?, String?, String?, Boolean?> {

    open var id: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var description: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsStandard")
    open var isStandard: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Long?, String?, String?, Boolean?> = super.fieldsRow() as Row4<Long?, String?, String?, Boolean?>
    override fun valuesRow(): Row4<Long?, String?, String?, Boolean?> = super.valuesRow() as Row4<Long?, String?, String?, Boolean?>
    override fun field1(): Field<Long?> = Role.ROLE.ID
    override fun field2(): Field<String?> = Role.ROLE.NAME
    override fun field3(): Field<String?> = Role.ROLE.DESCRIPTION
    override fun field4(): Field<Boolean?> = Role.ROLE.IS_STANDARD
    override fun component1(): Long = id
    override fun component2(): String = name
    override fun component3(): String = description
    override fun component4(): Boolean? = isStandard
    override fun value1(): Long = id
    override fun value2(): String = name
    override fun value3(): String = description
    override fun value4(): Boolean? = isStandard

    override fun value1(value: Long?): RoleRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): RoleRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): RoleRecord {
        set(2, value)
        return this
    }

    override fun value4(value: Boolean?): RoleRecord {
        set(3, value)
        return this
    }

    override fun values(value1: Long?, value2: String?, value3: String?, value4: Boolean?): RoleRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    constructor(id: Long, name: String, description: String, isStandard: Boolean? = null): this() {
        this.id = id
        this.name = name
        this.description = description
        this.isStandard = isStandard
        resetChangedOnNotNull()
    }
}
