/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.tables.records


import by.anatolyloyko.ams.orm.jooq.schemas.administration.tables.RolePermissions

import org.jooq.Field
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RolePermissionsRecord private constructor() : TableRecordImpl<RolePermissionsRecord>(RolePermissions.ROLE_PERMISSIONS), Record2<Long?, Long?> {

    open var roleId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var permissionId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<Long?, Long?> = super.fieldsRow() as Row2<Long?, Long?>
    override fun valuesRow(): Row2<Long?, Long?> = super.valuesRow() as Row2<Long?, Long?>
    override fun field1(): Field<Long?> = RolePermissions.ROLE_PERMISSIONS.ROLE_ID
    override fun field2(): Field<Long?> = RolePermissions.ROLE_PERMISSIONS.PERMISSION_ID
    override fun component1(): Long? = roleId
    override fun component2(): Long? = permissionId
    override fun value1(): Long? = roleId
    override fun value2(): Long? = permissionId

    override fun value1(value: Long?): RolePermissionsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Long?): RolePermissionsRecord {
        set(1, value)
        return this
    }

    override fun values(value1: Long?, value2: Long?): RolePermissionsRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised RolePermissionsRecord
     */
    constructor(roleId: Long? = null, permissionId: Long? = null): this() {
        this.roleId = roleId
        this.permissionId = permissionId
        resetChangedOnNotNull()
    }
}
