/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.users


import by.anatolyloyko.ams.orm.jooq.schemas.users.tables.User
import by.anatolyloyko.ams.orm.jooq.schemas.users.tables.UserPassword

import kotlin.collections.List

import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Users : SchemaImpl("users", null) {
    companion object {

        /**
         * The reference instance of <code>users</code>
         */
        val USERS: Users = Users()
    }

    /**
     * The table <code>users.user</code>.
     */
    val USER: User get() = User.USER

    /**
     * The table <code>users.user_password</code>.
     */
    val USER_PASSWORD: UserPassword get() = UserPassword.USER_PASSWORD

    override fun getTables(): List<Table<*>> = listOf(
        User.USER,
        UserPassword.USER_PASSWORD
    )
}
