/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.users.routines


import by.anatolyloyko.ams.orm.jooq.schemas.users.Users

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateUser : AbstractRoutine<java.lang.Void>("create_user", Users.USERS) {
    companion object {

        /**
         * The parameter <code>users.create_user._id</code>.
         */
        val _ID: Parameter<Long?> = Internal.createParameter("_id", SQLDataType.BIGINT, false, false)
    }

    init {
        addInParameter(CreateUser._ID)
    }

    /**
     * Set the <code>_id</code> parameter IN value to the routine
     */
    fun set_Id(value: Long?): Unit = setValue(CreateUser._ID, value)
}
