debug: false
spring:
    main:
        allow-bean-definition-overriding: false
    output:
        ansi:
            enabled: always
    graphql:
        graphiql:
            enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DBHOST:localhost}:${DBPORT:5442}/${DBNAME:brand_db}
        username: ${DBUSER:brsportal}
        password: ${DBPASS:brsportal}
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.LongSerializer
            value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            properties:
                schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:9081}
                enable.idempotence: false
                acks: all

ams:
    kafka:
        topic:
            brand:
                name: ${KAFKA_BRAND_EVENTS_TOPIC:v1.brands.brand}
                partitions: ${KAFKA_BRAND_EVENTS_TOPIC_PARTITIONS_COUNT:3}
                replicas: ${KAFKA_BRAND_EVENTS_TOPIC_REPLICATION_FACTOR:1}

        props:
            nack-cooldown: 100ms

management:
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            probes:
                enabled: true

logging:
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){cyan} - %clr(%-5level){yellow} %clr(%logger{36}){green} - %msg%n"
    level:
        org.jooq: DEBUG
        org.springframework: INFO
        by.anatolyloyko: DEBUG
        org.zalando.logbook.Logbook: TRACE
    file:
        name: log/brand-service.log
