/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.tables.references


import by.anatolyloyko.ams.orm.jooq.tables.Brand



/**
 * The table <code>brands.brand</code>.
 */
val BRAND: Brand = Brand.BRAND
