/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.brands.routines.references


import by.anatolyloyko.ams.orm.jooq.schemas.brands.routines.CreateBrand

import org.jooq.Configuration



/**
 * Call <code>brands.create_brand</code>
 */
fun createBrand(
      configuration: Configuration
    , _Id: Long?
): Unit {
    val p = CreateBrand()
    p.set_Id(_Id)

    p.execute(configuration)
}
