service:
  image:
    repository: "ghcr.io/tvoe-zdorovje/ams/administration-service"
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: github-registry

  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 888Mi
      limits:
        memory: 888Mi

    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15
      failureThreshold: 3
      successThreshold: 1

    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15
      failureThreshold: 3
      successThreshold: 1

    startupProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 15
      successThreshold: 1

  service:
    type: ClusterIP
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP

  cm:
    env:
      SERVER_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: "kafka-kafka-bootstrap.kafka.svc.cluster.local:29092"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry.kafka.svc.cluster.local:8081"
      KAFKA_GROUP_ID: "administration-service"
      KAFKA_TOPIC_BRAND: "v1.brands.brand"
      KAFKA_TOPIC_STUDIO: "v1.studios.studio"

      SPRING_CONFIG_IMPORT: "configserver:http://config-server.infrastructure.svc.cluster.local:8888"
      SPRING_CLOUD_CONFIG_FAIL_FAST: true
      SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS: 10
      SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL: 15000
      SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER: 1.2
      SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL: 1000
      SPRING_CLOUD_CONFIG_LABEL: master
# stored in secrets
#      DBHOST: administration_db
#      DBPORT: 5432
#      DBNAME: administration_db

  secrets:
    - name: administration-service-postgresql
