spring:
  application:
    name: auth-service
  datasource:
    user-db:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://${USSDBHOST}:${USSDBPORT}/${USSDBNAME}
      username: ${DBUSER}
      password: ${DBPASS}
    administration-db:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://${ADSDBHOST}:${ADSDBPORT}/${ADSDBNAME}
      username: ${DBUSER}
      password: ${DBPASS}
  data:
    redis:
      connect-timeout: 3s
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 3s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: manual
      missing-topics-fatal: false

ams:
  redis:
    topic:
      user-tokens:
        key-prefix: ${REDIS_USER_TOKENS_KEY_PREFIX}
  kafka:
    topic:
      keycloak-events:
        name: ${KAFKA_KEYCLOAK_EVENTS_TOPIC}
        event-types: ${KAFKA_KEYCLOAK_EVENTS_LIST}
      administration-user:
        name: ${KAFKA_ADMINISTRATION_USER_EVENTS_TOPIC}
        event-types: ${KAFKA_ADMINISTRATION_USER_EVENTS_LIST}
    props:
      nack-cooldown: ${KAFKA_NACK_COOLDOWN:100ms}

jwt:
  time-of-life: ${JWT_TTL}
  algorithm: RS256
  private-key:
    kid-format: "kid-%d"
    rotation:
      vault-size: ${VAULT_SIZE}
      period: ${JWKS_ROTATION_PERIOD}
