apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "default.labels" . | indent 4 }}
  annotations:
    {{- include "default.annotations" . | indent 4 }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
  {{- range $value := .Values.keycloak.service.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol }}
      name: {{ $value.name | default "service" }}
      {{- if and (eq $.Values.keycloak.service.type "NodePort") $value.nodePort }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
