package `by`.anatolyloyko.ams.orm.exposed.schemas.users.function

import kotlin.Long
import kotlin.String
import kotlin.Suppress
import org.jetbrains.exposed.sql.CustomFunction
import org.jetbrains.exposed.sql.LongColumnType
import org.jetbrains.exposed.sql.QueryParameter
import org.jetbrains.exposed.sql.VarCharColumnType

/**
 *
 *  *  ██████████████████████████ DO NOT MODIFY! █████████████████████████
 *  *  █                                             
 *  *  █                    It's an autogenerated file.
 *  *  █     To regenerate, execute:
 *  *  █ ./gradlew :user-service:generateDatabaseSchema
 *  *  █
 *  *  ███████████████████████████████████████████████████████████████████
 *
 *  Represents the 
 * 	"users.create_user" function in the database.
 *  
 *  Defines the structure to facilitate database operations using the Exposed library.
 */
@Suppress("MagicNumber", "ConstructorParameterNaming")
internal class CreateUserFunction(
  iPassword: String?,
  iFirstName: String?,
  iLastName: String?,
  iPhoneNumber: String?,
) : CustomFunction<Long>(
	"users.create_user", 
	LongColumnType(), 
	QueryParameter(iPassword, VarCharColumnType().apply { nullable = true }), 
	QueryParameter(iFirstName, VarCharColumnType().apply { nullable = true }), 
	QueryParameter(iLastName, VarCharColumnType().apply { nullable = true }), 
	QueryParameter(iPhoneNumber, VarCharColumnType().apply { nullable = true }), 
)
