/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.users.tables


import by.anatolyloyko.ams.orm.jooq.schemas.users.Users
import by.anatolyloyko.ams.orm.jooq.schemas.users.tables.records.UserPasswordRecord

import java.util.function.Function

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserPassword(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserPasswordRecord>?,
    parentPath: InverseForeignKey<out Record, UserPasswordRecord>?,
    aliased: Table<UserPasswordRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserPasswordRecord>(
    alias,
    Users.USERS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>users.user_password</code>
         */
        val USER_PASSWORD: UserPassword = UserPassword()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserPasswordRecord> = UserPasswordRecord::class.java

    /**
     * The column <code>users.user_password.user_id</code>.
     */
    val USER_ID: TableField<UserPasswordRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>users.user_password.password</code>.
     */
    val PASSWORD: TableField<UserPasswordRecord, String?> = createField(DSL.name("password"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserPasswordRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserPasswordRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)

    /**
     * Create an aliased <code>users.user_password</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>users.user_password</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>users.user_password</code> table reference
     */
    constructor(): this(DSL.name("user_password"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Users.USERS

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Long?, String?> = super.fieldsRow() as Row2<Long?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
