apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-schemas-pvc
spec:
  accessModes:
    - {{ .Values.service.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.service.persistence.storage }}
  volumeName: {{ .Release.Name }}-schemas-pv
  storageClassName: {{ .Values.service.persistence.storageClass }}
