/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AssetRolesBelongTo : AbstractRoutine<java.lang.Void>("asset_roles_belong_to", Administration.ADMINISTRATION) {
    companion object {

        /**
         * The parameter
         * <code>administration.asset_roles_belong_to.i_organization_id</code>.
         */
        val I_ORGANIZATION_ID: Parameter<Long?> = Internal.createParameter("i_organization_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.asset_roles_belong_to.i_roles</code>.
         */
        val I_ROLES: Parameter<Array<Long?>?> = Internal.createParameter("i_roles", SQLDataType.BIGINT.array(), false, false)
    }

    init {
        addInParameter(AssetRolesBelongTo.I_ORGANIZATION_ID)
        addInParameter(AssetRolesBelongTo.I_ROLES)
    }

    /**
     * Set the <code>i_organization_id</code> parameter IN value to the routine
     */
    fun setIOrganizationId(value: Long?): Unit = setValue(AssetRolesBelongTo.I_ORGANIZATION_ID, value)

    /**
     * Set the <code>i_roles</code> parameter IN value to the routine
     */
    fun setIRoles(value: Array<Long?>?): Unit = setValue(AssetRolesBelongTo.I_ROLES, value)
}
