/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateStudio : AbstractRoutine<Long>("create_studio", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter <code>administration.create_studio.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.create_studio.i_studio_id</code>.
         */
        val I_STUDIO_ID: Parameter<Long?> = Internal.createParameter("i_studio_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.create_studio.i_user_id</code>.
         */
        val I_USER_ID: Parameter<Long?> = Internal.createParameter("i_user_id", SQLDataType.BIGINT, false, false)
    }

    init {
        returnParameter = CreateStudio.RETURN_VALUE
        addInParameter(CreateStudio.I_STUDIO_ID)
        addInParameter(CreateStudio.I_USER_ID)
    }

    /**
     * Set the <code>i_studio_id</code> parameter IN value to the routine
     */
    fun setIStudioId(value: Long?): Unit = setValue(CreateStudio.I_STUDIO_ID, value)

    /**
     * Set the <code>i_studio_id</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setIStudioId(field: Field<Long?>): Unit {
        setField(CreateStudio.I_STUDIO_ID, field)
    }

    /**
     * Set the <code>i_user_id</code> parameter IN value to the routine
     */
    fun setIUserId(value: Long?): Unit = setValue(CreateStudio.I_USER_ID, value)

    /**
     * Set the <code>i_user_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIUserId(field: Field<Long?>): Unit {
        setField(CreateStudio.I_USER_ID, field)
    }
}
