/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateBrand : AbstractRoutine<Long>("create_brand", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter <code>administration.create_brand.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.create_brand.i_brand_id</code>.
         */
        val I_BRAND_ID: Parameter<Long?> = Internal.createParameter("i_brand_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.create_brand.i_user_id</code>.
         */
        val I_USER_ID: Parameter<Long?> = Internal.createParameter("i_user_id", SQLDataType.BIGINT, false, false)
    }

    init {
        returnParameter = CreateBrand.RETURN_VALUE
        addInParameter(CreateBrand.I_BRAND_ID)
        addInParameter(CreateBrand.I_USER_ID)
    }

    /**
     * Set the <code>i_brand_id</code> parameter IN value to the routine
     */
    fun setIBrandId(value: Long?): Unit = setValue(CreateBrand.I_BRAND_ID, value)

    /**
     * Set the <code>i_brand_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIBrandId(field: Field<Long?>): Unit {
        setField(CreateBrand.I_BRAND_ID, field)
    }

    /**
     * Set the <code>i_user_id</code> parameter IN value to the routine
     */
    fun setIUserId(value: Long?): Unit = setValue(CreateBrand.I_USER_ID, value)

    /**
     * Set the <code>i_user_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIUserId(field: Field<Long?>): Unit {
        setField(CreateBrand.I_USER_ID, field)
    }
}
