/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DeleteUserRoles : AbstractRoutine<Long>("delete_user_roles", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter
         * <code>administration.delete_user_roles.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.delete_user_roles.i_user_id</code>.
         */
        val I_USER_ID: Parameter<Long?> = Internal.createParameter("i_user_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.delete_user_roles.i_organization_id</code>.
         */
        val I_ORGANIZATION_ID: Parameter<Long?> = Internal.createParameter("i_organization_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.delete_user_roles.i_roles</code>.
         */
        val I_ROLES: Parameter<Array<Long?>?> = Internal.createParameter("i_roles", SQLDataType.BIGINT.array(), false, false)
    }

    init {
        returnParameter = DeleteUserRoles.RETURN_VALUE
        addInParameter(DeleteUserRoles.I_USER_ID)
        addInParameter(DeleteUserRoles.I_ORGANIZATION_ID)
        addInParameter(DeleteUserRoles.I_ROLES)
    }

    /**
     * Set the <code>i_user_id</code> parameter IN value to the routine
     */
    fun setIUserId(value: Long?): Unit = setValue(DeleteUserRoles.I_USER_ID, value)

    /**
     * Set the <code>i_user_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIUserId(field: Field<Long?>): Unit {
        setField(DeleteUserRoles.I_USER_ID, field)
    }

    /**
     * Set the <code>i_organization_id</code> parameter IN value to the routine
     */
    fun setIOrganizationId(value: Long?): Unit = setValue(DeleteUserRoles.I_ORGANIZATION_ID, value)

    /**
     * Set the <code>i_organization_id</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    fun setIOrganizationId(field: Field<Long?>): Unit {
        setField(DeleteUserRoles.I_ORGANIZATION_ID, field)
    }

    /**
     * Set the <code>i_roles</code> parameter IN value to the routine
     */
    fun setIRoles(value: Array<Long?>?): Unit = setValue(DeleteUserRoles.I_ROLES, value)

    /**
     * Set the <code>i_roles</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIRoles(field: Field<Array<Long?>?>): Unit {
        setField(DeleteUserRoles.I_ROLES, field)
    }
}
