/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.impl.AbstractRoutine


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RefreshFdwBrand : AbstractRoutine<java.lang.Void>("refresh_fdw_brand", Administration.ADMINISTRATION) {
    companion object {
    }

    init {
    }
}
