/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SetRolePermissions : AbstractRoutine<Long>("set_role_permissions", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter
         * <code>administration.set_role_permissions.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.set_role_permissions.i_role_id</code>.
         */
        val I_ROLE_ID: Parameter<Long?> = Internal.createParameter("i_role_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.set_role_permissions.i_permissions</code>.
         */
        val I_PERMISSIONS: Parameter<Array<Long?>?> = Internal.createParameter("i_permissions", SQLDataType.BIGINT.array(), false, false)
    }

    init {
        returnParameter = SetRolePermissions.RETURN_VALUE
        addInParameter(SetRolePermissions.I_ROLE_ID)
        addInParameter(SetRolePermissions.I_PERMISSIONS)
    }

    /**
     * Set the <code>i_role_id</code> parameter IN value to the routine
     */
    fun setIRoleId(value: Long?): Unit = setValue(SetRolePermissions.I_ROLE_ID, value)

    /**
     * Set the <code>i_role_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIRoleId(field: Field<Long?>): Unit {
        setField(SetRolePermissions.I_ROLE_ID, field)
    }

    /**
     * Set the <code>i_permissions</code> parameter IN value to the routine
     */
    fun setIPermissions(value: Array<Long?>?): Unit = setValue(SetRolePermissions.I_PERMISSIONS, value)

    /**
     * Set the <code>i_permissions</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setIPermissions(field: Field<Array<Long?>?>): Unit {
        setField(SetRolePermissions.I_PERMISSIONS, field)
    }
}
