/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SetStudioRoles : AbstractRoutine<Long>("set_studio_roles", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter
         * <code>administration.set_studio_roles.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.set_studio_roles.i_studio_id</code>.
         */
        val I_STUDIO_ID: Parameter<Long?> = Internal.createParameter("i_studio_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.set_studio_roles.i_roles</code>.
         */
        val I_ROLES: Parameter<Array<Long?>?> = Internal.createParameter("i_roles", SQLDataType.BIGINT.array(), false, false)
    }

    init {
        returnParameter = SetStudioRoles.RETURN_VALUE
        addInParameter(SetStudioRoles.I_STUDIO_ID)
        addInParameter(SetStudioRoles.I_ROLES)
    }

    /**
     * Set the <code>i_studio_id</code> parameter IN value to the routine
     */
    fun setIStudioId(value: Long?): Unit = setValue(SetStudioRoles.I_STUDIO_ID, value)

    /**
     * Set the <code>i_studio_id</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setIStudioId(field: Field<Long?>): Unit {
        setField(SetStudioRoles.I_STUDIO_ID, field)
    }

    /**
     * Set the <code>i_roles</code> parameter IN value to the routine
     */
    fun setIRoles(value: Array<Long?>?): Unit = setValue(SetStudioRoles.I_ROLES, value)

    /**
     * Set the <code>i_roles</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIRoles(field: Field<Array<Long?>?>): Unit {
        setField(SetStudioRoles.I_ROLES, field)
    }
}
