/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines


import by.anatolyloyko.ams.orm.jooq.schemas.administration.Administration

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SetStudioOwner : AbstractRoutine<java.lang.Void>("set_studio_owner", Administration.ADMINISTRATION) {
    companion object {

        /**
         * The parameter
         * <code>administration.set_studio_owner.i_studio_id</code>.
         */
        val I_STUDIO_ID: Parameter<Long?> = Internal.createParameter("i_studio_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.set_studio_owner.i_user_id</code>.
         */
        val I_USER_ID: Parameter<Long?> = Internal.createParameter("i_user_id", SQLDataType.BIGINT, false, false)
    }

    init {
        addInParameter(SetStudioOwner.I_STUDIO_ID)
        addInParameter(SetStudioOwner.I_USER_ID)
        setSQLUsable(false)
    }

    /**
     * Set the <code>i_studio_id</code> parameter IN value to the routine
     */
    fun setIStudioId(value: Long?): Unit = setValue(SetStudioOwner.I_STUDIO_ID, value)

    /**
     * Set the <code>i_user_id</code> parameter IN value to the routine
     */
    fun setIUserId(value: Long?): Unit = setValue(SetStudioOwner.I_USER_ID, value)
}
