/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.tables


import by.anatolyloyko.ams.orm.jooq.Brands
import by.anatolyloyko.ams.orm.jooq.tables.records.BrandRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Brand(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BrandRecord>?,
    parentPath: InverseForeignKey<out Record, BrandRecord>?,
    aliased: Table<BrandRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BrandRecord>(
    alias,
    Brands.BRANDS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>brands.brand</code>
         */
        val BRAND: Brand = Brand()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BrandRecord> = BrandRecord::class.java

    /**
     * The column <code>brands.brand.id</code>.
     */
    val ID: TableField<BrandRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>brands.brand.name</code>.
     */
    val NAME: TableField<BrandRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>brands.brand.description</code>.
     */
    val DESCRIPTION: TableField<BrandRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<BrandRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BrandRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)

    /**
     * Create an aliased <code>brands.brand</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>brands.brand</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>brands.brand</code> table reference
     */
    constructor(): this(DSL.name("brand"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Brands.BRANDS
    override fun getPrimaryKey(): UniqueKey<BrandRecord> = Internal.createUniqueKey(Brand.BRAND, DSL.name("brand_pkey"), arrayOf(Brand.BRAND.ID), true)
}
