/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.brands.routines.references


import by.anatolyloyko.ams.orm.jooq.schemas.brands.routines.CreateBrand
import by.anatolyloyko.ams.orm.jooq.schemas.brands.routines.UpdateBrand

import org.jooq.Configuration
import org.jooq.Field



/**
 * Call <code>brands.create_brand</code>
 */
fun createBrand(
      configuration: Configuration
    , iName: String?
    , iDescription: String?
): Long? {
    val f = CreateBrand()
    f.setIName(iName)
    f.setIDescription(iDescription)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>brands.create_brand</code> as a field.
 */
fun createBrand(
      iName: String?
    , iDescription: String?
): Field<Long?> {
    val f = CreateBrand()
    f.setIName(iName)
    f.setIDescription(iDescription)

    return f.asField()
}

/**
 * Get <code>brands.create_brand</code> as a field.
 */
fun createBrand(
      iName: Field<String?>
    , iDescription: Field<String?>
): Field<Long?> {
    val f = CreateBrand()
    f.setIName(iName)
    f.setIDescription(iDescription)

    return f.asField()
}

/**
 * Call <code>brands.update_brand</code>
 */
fun updateBrand(
      configuration: Configuration
    , iId: Long?
    , iName: String?
    , iDescription: String?
): Long? {
    val f = UpdateBrand()
    f.setIId(iId)
    f.setIName(iName)
    f.setIDescription(iDescription)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>brands.update_brand</code> as a field.
 */
fun updateBrand(
      iId: Long?
    , iName: String?
    , iDescription: String?
): Field<Long?> {
    val f = UpdateBrand()
    f.setIId(iId)
    f.setIName(iName)
    f.setIDescription(iDescription)

    return f.asField()
}

/**
 * Get <code>brands.update_brand</code> as a field.
 */
fun updateBrand(
      iId: Field<Long?>
    , iName: Field<String?>
    , iDescription: Field<String?>
): Field<Long?> {
    val f = UpdateBrand()
    f.setIId(iId)
    f.setIName(iName)
    f.setIDescription(iDescription)

    return f.asField()
}
