apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "default.labels" . | indent 4 }}
  annotations:
    {{- include "default.annotations" . | indent 4 }}
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: {{ .Chart.AppVersion | quote }}
    listeners:
      {{- toYaml .Values.kafka.listeners | nindent 6 }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
    {{- with .Values.kafka.livenessProbe }}
    livenessProbe:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.kafka.readinessProbe }}
    readinessProbe:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.kafka.startupProbe }}
    startupProbe:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.kafka.template }}
    template:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
  {{- with .Values.kafka.entityOperator }}
  entityOperator:
    {{- toYaml . | nindent 4 }}
  {{- end }}
