apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "default.labels" . | indent 4 }}
  annotations:
    {{- include "default.annotations" . | indent 4 }}
spec:
  clusterIP: None
  ports:
  {{- range $value := .Values.service.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol }}
    {{- if $value.name }}
      name: {{ $value.name }}
    {{- end }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
