/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq


import by.anatolyloyko.ams.orm.jooq.tables.Brand

import kotlin.collections.List

import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Brands : SchemaImpl("brands", null) {
    companion object {

        /**
         * The reference instance of <code>brands</code>
         */
        val BRANDS: Brands = Brands()
    }

    /**
     * The table <code>brands.brand</code>.
     */
    val BRAND: Brand get() = Brand.BRAND

    override fun getTables(): List<Table<*>> = listOf(
        Brand.BRAND
    )
}
