spring:
  main:
    allow-bean-definition-overriding: false
  output:
    ansi:
      enabled: always
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){cyan} - %clr(%-5level){yellow} %clr(%logger{36}){green} - %msg%n"
  level:
    org.springframework: INFO
    by.anatolyloyko: DEBUG
    org.zalando.logbook.Logbook: TRACE
  file:
    name: mylog.log
