/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.references


import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.AddBrandStudios
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.AddUserRoles
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.AssertRolesBelongTo
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.CreateBrandRole
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.CreateStandardRoleOwner
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.CreateStudioRole
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.DeleteUserRoles
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.SaveRole
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.SetBrandOwner
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.SetBrandRoles
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.SetRolePermissions
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.SetStudioOwner
import by.anatolyloyko.ams.orm.jooq.schemas.administration.routines.SetStudioRoles

import org.jooq.Configuration
import org.jooq.Field



/**
 * Call <code>administration.add_brand_studios</code>
 */
fun addBrandStudios(
      configuration: Configuration
    , iBrandId: Long?
    , iStudios: Array<Long?>?
): Long? {
    val f = AddBrandStudios()
    f.setIBrandId(iBrandId)
    f.setIStudios(iStudios)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.add_brand_studios</code> as a field.
 */
fun addBrandStudios(
      iBrandId: Long?
    , iStudios: Array<Long?>?
): Field<Long?> {
    val f = AddBrandStudios()
    f.setIBrandId(iBrandId)
    f.setIStudios(iStudios)

    return f.asField()
}

/**
 * Get <code>administration.add_brand_studios</code> as a field.
 */
fun addBrandStudios(
      iBrandId: Field<Long?>
    , iStudios: Field<Array<Long?>?>
): Field<Long?> {
    val f = AddBrandStudios()
    f.setIBrandId(iBrandId)
    f.setIStudios(iStudios)

    return f.asField()
}

/**
 * Call <code>administration.add_user_roles</code>
 */
fun addUserRoles(
      configuration: Configuration
    , iUserId: Long?
    , iOrganizationId: Long?
    , iRoles: Array<Long?>?
): Long? {
    val f = AddUserRoles()
    f.setIUserId(iUserId)
    f.setIOrganizationId(iOrganizationId)
    f.setIRoles(iRoles)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.add_user_roles</code> as a field.
 */
fun addUserRoles(
      iUserId: Long?
    , iOrganizationId: Long?
    , iRoles: Array<Long?>?
): Field<Long?> {
    val f = AddUserRoles()
    f.setIUserId(iUserId)
    f.setIOrganizationId(iOrganizationId)
    f.setIRoles(iRoles)

    return f.asField()
}

/**
 * Get <code>administration.add_user_roles</code> as a field.
 */
fun addUserRoles(
      iUserId: Field<Long?>
    , iOrganizationId: Field<Long?>
    , iRoles: Field<Array<Long?>?>
): Field<Long?> {
    val f = AddUserRoles()
    f.setIUserId(iUserId)
    f.setIOrganizationId(iOrganizationId)
    f.setIRoles(iRoles)

    return f.asField()
}

/**
 * Call <code>administration.assert_roles_belong_to</code>
 */
fun assertRolesBelongTo(
      configuration: Configuration
    , iOrganizationId: Long?
    , iRoles: Array<Long?>?
): Unit {
    val p = AssertRolesBelongTo()
    p.setIOrganizationId(iOrganizationId)
    p.setIRoles(iRoles)

    p.execute(configuration)
}

/**
 * Call <code>administration.create_brand_role</code>
 */
fun createBrandRole(
      configuration: Configuration
    , iBrandId: Long?
    , iName: String?
    , iDescription: String?
    , iPermissions: Array<Long?>?
): Long? {
    val f = CreateBrandRole()
    f.setIBrandId(iBrandId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.create_brand_role</code> as a field.
 */
fun createBrandRole(
      iBrandId: Long?
    , iName: String?
    , iDescription: String?
    , iPermissions: Array<Long?>?
): Field<Long?> {
    val f = CreateBrandRole()
    f.setIBrandId(iBrandId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Get <code>administration.create_brand_role</code> as a field.
 */
fun createBrandRole(
      iBrandId: Field<Long?>
    , iName: Field<String?>
    , iDescription: Field<String?>
    , iPermissions: Field<Array<Long?>?>
): Field<Long?> {
    val f = CreateBrandRole()
    f.setIBrandId(iBrandId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Call <code>administration.create_standard_role_owner</code>
 */
fun createStandardRoleOwner(
      configuration: Configuration
): Long? {
    val f = CreateStandardRoleOwner()

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.create_standard_role_owner</code> as a field.
 */
fun createStandardRoleOwner(): Field<Long?> {
    val f = CreateStandardRoleOwner()

    return f.asField()
}

/**
 * Call <code>administration.create_studio_role</code>
 */
fun createStudioRole(
      configuration: Configuration
    , iStudioId: Long?
    , iName: String?
    , iDescription: String?
    , iPermissions: Array<Long?>?
): Long? {
    val f = CreateStudioRole()
    f.setIStudioId(iStudioId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.create_studio_role</code> as a field.
 */
fun createStudioRole(
      iStudioId: Long?
    , iName: String?
    , iDescription: String?
    , iPermissions: Array<Long?>?
): Field<Long?> {
    val f = CreateStudioRole()
    f.setIStudioId(iStudioId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Get <code>administration.create_studio_role</code> as a field.
 */
fun createStudioRole(
      iStudioId: Field<Long?>
    , iName: Field<String?>
    , iDescription: Field<String?>
    , iPermissions: Field<Array<Long?>?>
): Field<Long?> {
    val f = CreateStudioRole()
    f.setIStudioId(iStudioId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Call <code>administration.delete_user_roles</code>
 */
fun deleteUserRoles(
      configuration: Configuration
    , iUserId: Long?
    , iOrganizationId: Long?
    , iRoles: Array<Long?>?
): Long? {
    val f = DeleteUserRoles()
    f.setIUserId(iUserId)
    f.setIOrganizationId(iOrganizationId)
    f.setIRoles(iRoles)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.delete_user_roles</code> as a field.
 */
fun deleteUserRoles(
      iUserId: Long?
    , iOrganizationId: Long?
    , iRoles: Array<Long?>?
): Field<Long?> {
    val f = DeleteUserRoles()
    f.setIUserId(iUserId)
    f.setIOrganizationId(iOrganizationId)
    f.setIRoles(iRoles)

    return f.asField()
}

/**
 * Get <code>administration.delete_user_roles</code> as a field.
 */
fun deleteUserRoles(
      iUserId: Field<Long?>
    , iOrganizationId: Field<Long?>
    , iRoles: Field<Array<Long?>?>
): Field<Long?> {
    val f = DeleteUserRoles()
    f.setIUserId(iUserId)
    f.setIOrganizationId(iOrganizationId)
    f.setIRoles(iRoles)

    return f.asField()
}

/**
 * Call <code>administration.save_role</code>
 */
fun saveRole(
      configuration: Configuration
    , iOrganizationId: Long?
    , iId: Long?
    , iName: String?
    , iDescription: String?
    , iPermissions: Array<Long?>?
): Long? {
    val f = SaveRole()
    f.setIOrganizationId(iOrganizationId)
    f.setIId(iId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.save_role</code> as a field.
 */
fun saveRole(
      iOrganizationId: Long?
    , iId: Long?
    , iName: String?
    , iDescription: String?
    , iPermissions: Array<Long?>?
): Field<Long?> {
    val f = SaveRole()
    f.setIOrganizationId(iOrganizationId)
    f.setIId(iId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Get <code>administration.save_role</code> as a field.
 */
fun saveRole(
      iOrganizationId: Field<Long?>
    , iId: Field<Long?>
    , iName: Field<String?>
    , iDescription: Field<String?>
    , iPermissions: Field<Array<Long?>?>
): Field<Long?> {
    val f = SaveRole()
    f.setIOrganizationId(iOrganizationId)
    f.setIId(iId)
    f.setIName(iName)
    f.setIDescription(iDescription)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Call <code>administration.set_brand_owner</code>
 */
fun setBrandOwner(
      configuration: Configuration
    , iBrandId: Long?
    , iUserId: Long?
): Unit {
    val p = SetBrandOwner()
    p.setIBrandId(iBrandId)
    p.setIUserId(iUserId)

    p.execute(configuration)
}

/**
 * Call <code>administration.set_brand_roles</code>
 */
fun setBrandRoles(
      configuration: Configuration
    , iBrandId: Long?
    , iRoles: Array<Long?>?
): Long? {
    val f = SetBrandRoles()
    f.setIBrandId(iBrandId)
    f.setIRoles(iRoles)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.set_brand_roles</code> as a field.
 */
fun setBrandRoles(
      iBrandId: Long?
    , iRoles: Array<Long?>?
): Field<Long?> {
    val f = SetBrandRoles()
    f.setIBrandId(iBrandId)
    f.setIRoles(iRoles)

    return f.asField()
}

/**
 * Get <code>administration.set_brand_roles</code> as a field.
 */
fun setBrandRoles(
      iBrandId: Field<Long?>
    , iRoles: Field<Array<Long?>?>
): Field<Long?> {
    val f = SetBrandRoles()
    f.setIBrandId(iBrandId)
    f.setIRoles(iRoles)

    return f.asField()
}

/**
 * Call <code>administration.set_role_permissions</code>
 */
fun setRolePermissions(
      configuration: Configuration
    , iRoleId: Long?
    , iPermissions: Array<Long?>?
): Long? {
    val f = SetRolePermissions()
    f.setIRoleId(iRoleId)
    f.setIPermissions(iPermissions)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.set_role_permissions</code> as a field.
 */
fun setRolePermissions(
      iRoleId: Long?
    , iPermissions: Array<Long?>?
): Field<Long?> {
    val f = SetRolePermissions()
    f.setIRoleId(iRoleId)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Get <code>administration.set_role_permissions</code> as a field.
 */
fun setRolePermissions(
      iRoleId: Field<Long?>
    , iPermissions: Field<Array<Long?>?>
): Field<Long?> {
    val f = SetRolePermissions()
    f.setIRoleId(iRoleId)
    f.setIPermissions(iPermissions)

    return f.asField()
}

/**
 * Call <code>administration.set_studio_owner</code>
 */
fun setStudioOwner(
      configuration: Configuration
    , iStudioId: Long?
    , iUserId: Long?
): Unit {
    val p = SetStudioOwner()
    p.setIStudioId(iStudioId)
    p.setIUserId(iUserId)

    p.execute(configuration)
}

/**
 * Call <code>administration.set_studio_roles</code>
 */
fun setStudioRoles(
      configuration: Configuration
    , iStudioId: Long?
    , iRoles: Array<Long?>?
): Long? {
    val f = SetStudioRoles()
    f.setIStudioId(iStudioId)
    f.setIRoles(iRoles)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>administration.set_studio_roles</code> as a field.
 */
fun setStudioRoles(
      iStudioId: Long?
    , iRoles: Array<Long?>?
): Field<Long?> {
    val f = SetStudioRoles()
    f.setIStudioId(iStudioId)
    f.setIRoles(iRoles)

    return f.asField()
}

/**
 * Get <code>administration.set_studio_roles</code> as a field.
 */
fun setStudioRoles(
      iStudioId: Field<Long?>
    , iRoles: Field<Array<Long?>?>
): Field<Long?> {
    val f = SetStudioRoles()
    f.setIStudioId(iStudioId)
    f.setIRoles(iRoles)

    return f.asField()
}
