/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas


import by.anatolyloyko.ams.orm.jooq.schemas.tables.Appointment

import kotlin.collections.List

import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Appointments : SchemaImpl("appointments", null) {
    companion object {

        /**
         * The reference instance of <code>appointments</code>
         */
        val APPOINTMENTS: Appointments = Appointments()
    }

    /**
     * The table <code>appointments.appointment</code>.
     */
    val APPOINTMENT: Appointment get() = Appointment.APPOINTMENT

    override fun getTables(): List<Table<*>> = listOf(
        Appointment.APPOINTMENT
    )
}
