apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
  annotations:
    {{- include "default.annotations" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.schemaRegistry.cm.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
