/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.tables.references


import by.anatolyloyko.ams.orm.jooq.schemas.tables.Appointment



/**
 * The table <code>appointments.appointment</code>.
 */
val APPOINTMENT: Appointment = Appointment.APPOINTMENT
