debug: false
server:
  port: 8181
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    allow-bean-definition-overriding: false
  output:
    ansi:
      enabled: always
  graphql:
    graphiql:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5441/administration_db
    username: adsportal
    password: adsportal
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: administration-service
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        schema.registry.url: http://schema-registry:8081
        specific.avro.reader: true
    listener:
      ack-mode: manual
      missing-topics-fatal: false

ams:
  kafka:
    topic:
      brand:
        name: v1.brands.brand
      studio:
        name: v1.studios.studio
    props:
      nack-cooldown: 100ms

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){cyan} - %clr(%-5level){yellow} %clr(%logger{36}){green} - %msg%n"
  level:
    org.jooq: DEBUG
    org.springframework: INFO
    by.anatolyloyko: DEBUG
    org.zalando.logbook.Logbook: TRACE
  file:
    name: /log/administration-service.log
