/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.tables.references


import by.anatolyloyko.ams.orm.jooq.schemas.tables.Studio



/**
 * The table <code>studios.studio</code>.
 */
val STUDIO: Studio = Studio.STUDIO
