service:
  deployment:
    replicas: 1
    imagePullSecrets:
      - name: github-registry
    router:
      image:
        repository: "ghcr.io/apollographql/router"
        tag: "v2.2.0"
        pullPolicy: IfNotPresent
        pullSecrets:
          - name: github-registry
      ports:
        - port: 4000
          protocol: TCP
      volumes:
        - name: router-config-volume
          mountPath: /dist/mnt
          claimName: gateway-router-config-pvc # prefix: .Release.Name
      resources:
        requests:
          cpu: 500m
          memory: 111Mi
        limits:
          memory: 333Mi
      livenessProbe:
        httpGet:
          path: "/health?live"
          port: 4000
      readinessProbe:
        httpGet:
          path: "/health?ready"
          port: 4000
    gateway:
      image:
        repository: "ghcr.io/tvoe-zdorovje/ams/gateway-service"
        tag: ""
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 500m
          memory: 670
        limits:
          memory: 670Mi
      ports:
        - port: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
        successThreshold: 1
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 15
        failureThreshold: 3
        successThreshold: 1

  service:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 4000
        protocol: TCP
        name: router
      - port: 8080 # dev only
        targetPort: 8080
        protocol: TCP
        name: gateway-service

  persistence:
    accessModes: ReadOnlyMany
    storage: 4Mi
    path: /gateway/router/build
    storageClass: manual

  ingress:
    host: ams.by
    path: /.*
    port: 80
    pathType: ImplementationSpecific

  cm:
    router:
      env:
        # apollo router config
        APOLLO_ROUTER_HOT_RELOAD: true
        APOLLO_ROUTER_INCLUDE_SUBGRAPH_ERRORS: true
        APOLLO_ROUTER_SUPERGRAPH_PATH: "/dist/mnt/schema/supergraph.graphql"
        APOLLO_ROUTER_CONFIG_PATH: "/dist/mnt/config/router.yaml"
        APOLLO_ROUTER_LISTEN_ADDRESS: "0.0.0.0:4000"
        APOLLO_ROUTER_HEALTH_CHECK_LISTEN_ADDRESS: "0.0.0.0:4000"

        # apollo router routes
        AUTH_SERVICE_SUBGRAPH: "http://127.0.0.1:8080/auth/graphql"
        ADMINISTRATION_SERVICE_SUBGRAPH: "http://127.0.0.1:8080/administration/graphql"
        APPOINTMENT_SERVICE_SUBGRAPH: "http://127.0.0.1:8080/appointment/graphql"
        BRAND_SERVICE_SUBGRAPH: "http://127.0.0.1:8080/brand/graphql"
        STUDIO_SERVICE_SUBGRAPH: "http://127.0.0.1:8080/studio/graphql"
        USER_SERVICE_SUBGRAPH: "http://127.0.0.1:8080/user/graphql"

    gateway:
      env:
        # gateway config
        GATEWAY_SERVICE_PORT: 8080
        GATEWAY_SERVICE_HOST: "127.0.0.1"
        # gateway routes
        AUTH_SERVICE_HOST: "http://auth-service:8080"
        ADMINISTRATION_SERVICE_HOST: "http://administration-service:8080"
        APPOINTMENT_SERVICE_HOST: "http://appointment-service:8080"
        BRAND_SERVICE_HOST: "http://brand-service:8080"
        STUDIO_SERVICE_HOST: "http://studio-service:8080"
        USER_SERVICE_HOST: "http://user-service:8080"
        JWKS_URI: "http://auth-service:8080/.well-known/jwks"
