/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.enums


import by.anatolyloyko.ams.orm.jooq.schemas.Appointments

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class AppointmentStatus(@get:JvmName("literal") public val literal: String) : EnumType {
    REQUESTED("REQUESTED"),
    CORRECTED("CORRECTED"),
    APPROVED("APPROVED"),
    COMPLETED("COMPLETED"),
    CANCELLED("CANCELLED");
    override fun getCatalog(): Catalog? = null
    override fun getSchema(): Schema = Appointments.APPOINTMENTS
    override fun getName(): String = "appointment_status"
    override fun getLiteral(): String = literal
}
