/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.users.routines.references


import by.anatolyloyko.ams.orm.jooq.schemas.users.routines.CreateUser
import by.anatolyloyko.ams.orm.jooq.schemas.users.routines.SaveUser

import org.jooq.Configuration
import org.jooq.Field



/**
 * Call <code>users.create_user</code>
 */
fun createUser(
      configuration: Configuration
    , iPassword: String?
    , iFirstName: String?
    , iLastName: String?
    , iPhoneNumber: String?
): Long? {
    val f = CreateUser()
    f.setIPassword(iPassword)
    f.setIFirstName(iFirstName)
    f.setILastName(iLastName)
    f.setIPhoneNumber(iPhoneNumber)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>users.create_user</code> as a field.
 */
fun createUser(
      iPassword: String?
    , iFirstName: String?
    , iLastName: String?
    , iPhoneNumber: String?
): Field<Long?> {
    val f = CreateUser()
    f.setIPassword(iPassword)
    f.setIFirstName(iFirstName)
    f.setILastName(iLastName)
    f.setIPhoneNumber(iPhoneNumber)

    return f.asField()
}

/**
 * Get <code>users.create_user</code> as a field.
 */
fun createUser(
      iPassword: Field<String?>
    , iFirstName: Field<String?>
    , iLastName: Field<String?>
    , iPhoneNumber: Field<String?>
): Field<Long?> {
    val f = CreateUser()
    f.setIPassword(iPassword)
    f.setIFirstName(iFirstName)
    f.setILastName(iLastName)
    f.setIPhoneNumber(iPhoneNumber)

    return f.asField()
}

/**
 * Call <code>users.save_user</code>
 */
fun saveUser(
      configuration: Configuration
    , iId: Long?
    , iFirstName: String?
    , iLastName: String?
    , iPhoneNumber: String?
): Long? {
    val f = SaveUser()
    f.setIId(iId)
    f.setIFirstName(iFirstName)
    f.setILastName(iLastName)
    f.setIPhoneNumber(iPhoneNumber)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>users.save_user</code> as a field.
 */
fun saveUser(
      iId: Long?
    , iFirstName: String?
    , iLastName: String?
    , iPhoneNumber: String?
): Field<Long?> {
    val f = SaveUser()
    f.setIId(iId)
    f.setIFirstName(iFirstName)
    f.setILastName(iLastName)
    f.setIPhoneNumber(iPhoneNumber)

    return f.asField()
}

/**
 * Get <code>users.save_user</code> as a field.
 */
fun saveUser(
      iId: Field<Long?>
    , iFirstName: Field<String?>
    , iLastName: Field<String?>
    , iPhoneNumber: Field<String?>
): Field<Long?> {
    val f = SaveUser()
    f.setIId(iId)
    f.setIFirstName(iFirstName)
    f.setILastName(iLastName)
    f.setIPhoneNumber(iPhoneNumber)

    return f.asField()
}
