{{- define "common.umbrella.secret" }}
{{- range .Values.global.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secrets[].name is required" .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "default.labels" $ | nindent 4 }}
  annotations:
    {{- include "default.annotations" $ | nindent 4 }}
type: {{ required "secrets[].type is required" .type | quote }}
data:
  {{- range $key, $value := .data }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}