/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.routines


import by.anatolyloyko.ams.orm.jooq.schemas.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AddBrandStudios : AbstractRoutine<Long>("add_brand_studios", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter
         * <code>administration.add_brand_studios.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.add_brand_studios.i_brand_id</code>.
         */
        val I_BRAND_ID: Parameter<Long?> = Internal.createParameter("i_brand_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter
         * <code>administration.add_brand_studios.i_studios</code>.
         */
        val I_STUDIOS: Parameter<Array<Long?>?> = Internal.createParameter("i_studios", SQLDataType.BIGINT.array(), false, false)
    }

    init {
        returnParameter = AddBrandStudios.RETURN_VALUE
        addInParameter(AddBrandStudios.I_BRAND_ID)
        addInParameter(AddBrandStudios.I_STUDIOS)
    }

    /**
     * Set the <code>i_brand_id</code> parameter IN value to the routine
     */
    fun setIBrandId(value: Long?): Unit = setValue(AddBrandStudios.I_BRAND_ID, value)

    /**
     * Set the <code>i_brand_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIBrandId(field: Field<Long?>): Unit {
        setField(AddBrandStudios.I_BRAND_ID, field)
    }

    /**
     * Set the <code>i_studios</code> parameter IN value to the routine
     */
    fun setIStudios(value: Array<Long?>?): Unit = setValue(AddBrandStudios.I_STUDIOS, value)

    /**
     * Set the <code>i_studios</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIStudios(field: Field<Array<Long?>?>): Unit {
        setField(AddBrandStudios.I_STUDIOS, field)
    }
}
