/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.routines


import by.anatolyloyko.ams.orm.jooq.schemas.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SaveRole : AbstractRoutine<Long>("save_role", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter <code>administration.save_role.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.save_role.i_id</code>.
         */
        val I_ID: Parameter<Long?> = Internal.createParameter("i_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.save_role.i_name</code>.
         */
        val I_NAME: Parameter<String?> = Internal.createParameter("i_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>administration.save_role.i_description</code>.
         */
        val I_DESCRIPTION: Parameter<String?> = Internal.createParameter("i_description", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>administration.save_role.i_permissions</code>.
         */
        val I_PERMISSIONS: Parameter<Array<Long?>?> = Internal.createParameter("i_permissions", SQLDataType.BIGINT.array(), false, false)
    }

    init {
        returnParameter = SaveRole.RETURN_VALUE
        addInParameter(SaveRole.I_ID)
        addInParameter(SaveRole.I_NAME)
        addInParameter(SaveRole.I_DESCRIPTION)
        addInParameter(SaveRole.I_PERMISSIONS)
    }

    /**
     * Set the <code>i_id</code> parameter IN value to the routine
     */
    fun setIId(value: Long?): Unit = setValue(SaveRole.I_ID, value)

    /**
     * Set the <code>i_id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIId(field: Field<Long?>): Unit {
        setField(SaveRole.I_ID, field)
    }

    /**
     * Set the <code>i_name</code> parameter IN value to the routine
     */
    fun setIName(value: String?): Unit = setValue(SaveRole.I_NAME, value)

    /**
     * Set the <code>i_name</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIName(field: Field<String?>): Unit {
        setField(SaveRole.I_NAME, field)
    }

    /**
     * Set the <code>i_description</code> parameter IN value to the routine
     */
    fun setIDescription(value: String?): Unit = setValue(SaveRole.I_DESCRIPTION, value)

    /**
     * Set the <code>i_description</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setIDescription(field: Field<String?>): Unit {
        setField(SaveRole.I_DESCRIPTION, field)
    }

    /**
     * Set the <code>i_permissions</code> parameter IN value to the routine
     */
    fun setIPermissions(value: Array<Long?>?): Unit = setValue(SaveRole.I_PERMISSIONS, value)

    /**
     * Set the <code>i_permissions</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setIPermissions(field: Field<Array<Long?>?>): Unit {
        setField(SaveRole.I_PERMISSIONS, field)
    }
}
