/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.routines


import by.anatolyloyko.ams.orm.jooq.schemas.Administration

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SetBrandRoles : AbstractRoutine<Long>("set_brand_roles", Administration.ADMINISTRATION, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter
         * <code>administration.set_brand_roles.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.set_brand_roles.i_brand_id</code>.
         */
        val I_BRAND_ID: Parameter<Long?> = Internal.createParameter("i_brand_id", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>administration.set_brand_roles.i_roles</code>.
         */
        val I_ROLES: Parameter<Array<Long?>?> = Internal.createParameter("i_roles", SQLDataType.BIGINT.array(), false, false)
    }

    init {
        returnParameter = SetBrandRoles.RETURN_VALUE
        addInParameter(SetBrandRoles.I_BRAND_ID)
        addInParameter(SetBrandRoles.I_ROLES)
    }

    /**
     * Set the <code>i_brand_id</code> parameter IN value to the routine
     */
    fun setIBrandId(value: Long?): Unit = setValue(SetBrandRoles.I_BRAND_ID, value)

    /**
     * Set the <code>i_brand_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    fun setIBrandId(field: Field<Long?>): Unit {
        setField(SetBrandRoles.I_BRAND_ID, field)
    }

    /**
     * Set the <code>i_roles</code> parameter IN value to the routine
     */
    fun setIRoles(value: Array<Long?>?): Unit = setValue(SetBrandRoles.I_ROLES, value)

    /**
     * Set the <code>i_roles</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIRoles(field: Field<Array<Long?>?>): Unit {
        setField(SetBrandRoles.I_ROLES, field)
    }
}
