/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.routines.references


import by.anatolyloyko.ams.orm.jooq.schemas.routines.CreateAppointment

import java.util.UUID

import org.jooq.Configuration
import org.jooq.Field



/**
 * Call <code>appointments.create_appointment</code>
 */
fun createAppointment(
      configuration: Configuration
    , iDescription: String?
    , iClientUserId: Long?
    , iMasterUserId: Long?
    , iManagerUserId: Long?
    , iStudioId: Long?
    , iComment: String?
): UUID? {
    val f = CreateAppointment()
    f.setIDescription(iDescription)
    f.setIClientUserId(iClientUserId)
    f.setIMasterUserId(iMasterUserId)
    f.setIManagerUserId(iManagerUserId)
    f.setIStudioId(iStudioId)
    f.setIComment(iComment)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>appointments.create_appointment</code> as a field.
 */
fun createAppointment(
      iDescription: String?
    , iClientUserId: Long?
    , iMasterUserId: Long?
    , iManagerUserId: Long?
    , iStudioId: Long?
    , iComment: String?
): Field<UUID?> {
    val f = CreateAppointment()
    f.setIDescription(iDescription)
    f.setIClientUserId(iClientUserId)
    f.setIMasterUserId(iMasterUserId)
    f.setIManagerUserId(iManagerUserId)
    f.setIStudioId(iStudioId)
    f.setIComment(iComment)

    return f.asField()
}

/**
 * Get <code>appointments.create_appointment</code> as a field.
 */
fun createAppointment(
      iDescription: Field<String?>
    , iClientUserId: Field<Long?>
    , iMasterUserId: Field<Long?>
    , iManagerUserId: Field<Long?>
    , iStudioId: Field<Long?>
    , iComment: Field<String?>
): Field<UUID?> {
    val f = CreateAppointment()
    f.setIDescription(iDescription)
    f.setIClientUserId(iClientUserId)
    f.setIMasterUserId(iMasterUserId)
    f.setIManagerUserId(iManagerUserId)
    f.setIStudioId(iStudioId)
    f.setIComment(iComment)

    return f.asField()
}
