/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.studios.routines.references


import by.anatolyloyko.ams.orm.jooq.schemas.studios.routines.CreateStudio

import org.jooq.Configuration



/**
 * Call <code>studios.create_studio</code>
 */
fun createStudio(
      configuration: Configuration
    , _Id: Long?
): Unit {
    val p = CreateStudio()
    p.set_Id(_Id)

    p.execute(configuration)
}
