/*
 * This file is generated by jOOQ.
 */
package by.anatolyloyko.ams.orm.jooq.schemas.studios.routines


import by.anatolyloyko.ams.orm.jooq.schemas.studios.Studios

import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CreateStudio : AbstractRoutine<Long>("create_studio", Studios.STUDIOS, SQLDataType.BIGINT) {
    companion object {

        /**
         * The parameter <code>studios.create_studio.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Long?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false)

        /**
         * The parameter <code>studios.create_studio.i_name</code>.
         */
        val I_NAME: Parameter<String?> = Internal.createParameter("i_name", SQLDataType.VARCHAR, false, false)

        /**
         * The parameter <code>studios.create_studio.i_description</code>.
         */
        val I_DESCRIPTION: Parameter<String?> = Internal.createParameter("i_description", SQLDataType.VARCHAR, false, false)
    }

    init {
        returnParameter = CreateStudio.RETURN_VALUE
        addInParameter(CreateStudio.I_NAME)
        addInParameter(CreateStudio.I_DESCRIPTION)
    }

    /**
     * Set the <code>i_name</code> parameter IN value to the routine
     */
    fun setIName(value: String?): Unit = setValue(CreateStudio.I_NAME, value)

    /**
     * Set the <code>i_name</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun setIName(field: Field<String?>): Unit {
        setField(CreateStudio.I_NAME, field)
    }

    /**
     * Set the <code>i_description</code> parameter IN value to the routine
     */
    fun setIDescription(value: String?): Unit = setValue(CreateStudio.I_DESCRIPTION, value)

    /**
     * Set the <code>i_description</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    fun setIDescription(field: Field<String?>): Unit {
        setField(CreateStudio.I_DESCRIPTION, field)
    }
}
